name: AdminUtils
version: ${project.version}
main: me.waldxn.adminutils.AdminUtils
author: Waldxn
commands:
  mute:
    description: Mute a player
  unmute:
    description: Unmute a player
  nickname:
    description: Give player a nickname
  freeze:
    description: Freeze a specific player
  unfreeze:
    description: Unfreeze a specific player
  freezeall:
    description: Freeze the entire server
  unfreezeall:
    description: Unfreeze the entire server
permissions:
  utils.mute:
    description: Permission node to /mute, /unmute
  utils.nickname:
    description: Permission node to /nickname
  utils.nickname.others:
    description: Permission node to /nickname [nickname] [target-player]
  utils.freeze:
    description: Permission node to /freeze, /unfreeze
  utils.freezeall:
    description: Permission node to /freezeall, /unfreezeall